### ISSUE TITLE
Add qtransfer as standard functionality to the Monitor

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#11]
Add qtransfer as standard functionality to the Monitor

**Comment by sy2002** [comment]
Added to scope of issue #28, i.e. release 1.6

**Comment by sy2002** [comment]
Do that in the `develop` branch after all the other branches were merged back down to `develop`

**Comment by sy2002** [comment]
* After this is done, we also need to update the documentation about qtransfer in `doc/README.md`.
* Also, from this moment on, we might build it by default in `tools/make-toolchain.sh` and only if the serial library is missing, we would output the instructoins of how to build it manually (as we do it today).

**Comment by MJoergen** [comment]
> Also, from this moment on, we might build it by default in `tools/make-toolchain.sh` and only if the serial library is missing, we would output the instructoins of how to build it manually (as we do it today).

Yes, please do that. It seems strange that it is not built automatically.

**Comment by sy2002** [comment]
done
