### ISSUE TITLE
Do we have a problem with the color white?

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#117]
### Do we have a problem with the color white?

It might be that this is just an "optical illusion" on my setup. If so, then just comment and close.

But on my screen, white looks like **light gray** and not like white. It feels like we are not using all color bits that the Nexys 4 board is able to provide but that's as said, more a gut feeling.

How to reproduce:

1. Pull the latest `develop` branch and run `tools/make_toolchain.sh`
2. Run `test_programs/fancy.asm`  (start address is `FA00`)
3. Press `f`
4. Observe the background color that looks more like light gray on my screen than white
5. Run `FA30` to switch the fanciness off  (`C` `R` `FA30`)

**Comment by MJoergen** [comment]
On my monitor it looks bright white. I see no problems with the colours produced on Nexys4DDR. => Closed.
