### ISSUE TITLE
Cursor of new VGA module is erasing characters under it

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#124]
How to reproduce:

1. Switch STDIN=STDOUT=UART on the Nexys board by switching OFF `SW0` and `SW1`.
2. Press reset.
3. You will notice, that the character `Q` is not there any more, but so instead of `QNICE` it says ` NICE` and the cursor is blinking at the spot where the `Q` would normally be.

I just cross-checked with `V1.6`, there it works correctly: If I run this sequence on V1.6, then I see `QNICE...` and the cursor is blinking over the "Q" by i**nverting the Q**, so it shows Q and then inverted Q and then Q and then inverted Q, ...

**Comment by MJoergen** [comment]
Fixed.
