### ISSUE TITLE
create_documentation.pl is not able to translate >= and < correctly

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#129]
I re-ran `monitor/create_documentation.pl` as we added a new "operating system function", so that our documentation in `doc/monitor/doc.pdf` is up to date. I noticed a problem about creating the correct LaTeX commands for `>=` and `<` (are there even more?)

Please look at the red arrows in this image:

<img width="789" alt="grafik" src="https://user-images.githubusercontent.com/6825267/93091458-664fe880-f69e-11ea-8a29-a4bc11852f37.png">

**Comment by bernd-ulmann** [comment]
I fixed create_documentation.pl so that < and > are now displayed properly. :-)
