### ISSUE TITLE
Assembler wastes one word per \t

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#137]
The improvement to replace a `\t` by only one character as described here https://github.com/sy2002/QNICE-FPGA/issues/132#issuecomment-692983812 has lead to a minor side effect:

The assembler is now wasting memory: One word per `\t`.

Please have a look at this visual diff that I did on the `.out` files:

I assembled the Monitor.

Left side: Assembled with the new assembler, right with the old one:

<img width="799" alt="grafik" src="https://user-images.githubusercontent.com/6825267/93270929-604b2c00-f7b2-11ea-9a73-34bdc0f1e37c.png">

As you can see, in both cases the assembler continues at address `0x0D9E`, but in the left case, it could have continued with `0x0D9C` instead, so two words are wasted for the

**Comment by bernd-ulmann** [comment]
Aw shucks... Fortunately, this was easy to fix. :-) Done and checked in. :-)
