### ISSUE TITLE
Proof-read the ISR best practices

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#140]
I volunteered to collect all our recent best-practice findings around ISRs.

Here they are:

https://github.com/sy2002/QNICE-FPGA/blob/develop/doc/best-practices.md#interrupt-service-routines-isrs

@MJoergen and @bernd-ulmann please proof read and feel free to improve this file: `doc/best-practices.md`.

Bonus: I also volunteered and collected all our recent best-practice findings around register banks:

https://github.com/sy2002/QNICE-FPGA/blob/develop/doc/best-practices.md#register-banks

After that, please close this issue.

**Comment by bernd-ulmann** [comment]
I really like the "be paranoid" part! :-) That is so true!

**Comment by MJoergen** [comment]
I've made a few minor updates to the `best-practices.md` document. I'm satisfied now.
