### ISSUE TITLE
Assembler lost ability to align within .lis file

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#148]
In one of the latest updates (I cannot point to which one from the top of my head), the assembler lost its ability to align within the `.lis` file which makes reading the `.lis` file harder. The following screenshot shows the problem:

<img width="820" alt="grafik" src="https://user-images.githubusercontent.com/6825267/94347797-9650a180-0037-11eb-9d28-1fe5d721b83f.png">

What seems to happen is: The code that comes behind a label is always printed with one space in the `.lis` file as opposed to the amount that was given in the source file.

**Comment by bernd-ulmann** [comment]
...to be honest, I have seen this quite some time ago but always forgot to fix it... I will try to take care of it tomorrow or Monday at latest. :-)

**Comment by bernd-ulmann** [comment]
Assembler listings now look qnice nice again. ;-)
