### ISSUE TITLE
demo_tree.c looks weird in emulator

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#151]
I updated the VBCC compiler and standard library as described in issue #100. I am not sure if this is a problem of the new VBCC or of the new emulator, so @MJoergen please investigate.

demo_tree.c looks like this in the emulator:

<img width="293" alt="grafik" src="https://user-images.githubusercontent.com/6825267/94993208-a7496780-058f-11eb-90cf-eba1712d176b.png">

**Comment by sy2002** [comment]
Update: Looks fine on hardware, so probably has nothing todo with new version of VBCC?

**Comment by MJoergen** [comment]
Fixed.
