### ISSUE TITLE
Emulator shows weird addresses in prompt

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#159]
Here is an example: A breakpoint is set to $8A20. After the breakpoint is reached, the prompt shows $8BA0.

<img width="430" alt="grafik" src="https://user-images.githubusercontent.com/6825267/95687146-195e2400-0c02-11eb-8247-cdbcf8cf366d.png">

A quick check using `rdump` shows, that the PC is indeed at $8A20 (where it should be), so the prompt is obviously wrong.

**Comment by bernd-ulmann** [comment]
Fixed (at least my simple breakpoint test worked). :-)

**Comment by sy2002** [comment]
@bernd-ulmann Basic smoke test fails: It is not possible to single step using `step` any more with this fix: How to reproduce:  Set breakpoint and then try to `step`.

**Comment by bernd-ulmann** [comment]
*sigh* I should not try to "fix" things so late at night... Please give it another try - it should work now... Sorry!

**Comment by sy2002** [comment]
will gladly try, but you need to PUSH your local git first :-)

**Comment by bernd-ulmann** [comment]
*ARGL* I did push but did not notice that it failed due to a merge required... I merged and pushed again... Time to go to bed, I think. :-)

**Comment by sy2002** [comment]
Works :-) 👍
