### ISSUE TITLE
Emulator kind of crashes after reset

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#161]
This one is **not** urgent as the situation can only be provoked, when working with the `reset` command of the emulator.

Here it is:

<img width="636" alt="grafik" src="https://user-images.githubusercontent.com/6825267/95690965-ca24ed00-0c1b-11eb-902b-8d6a47a13441.png">

**Comment by sy2002** [comment]
sorry, wrong reproduction scheme. closing.

**Comment by sy2002** [comment]
Well maybe it is the right reproduction scheme: @bernd-ulmann how should reset actually behave?

**Comment by bernd-ulmann** [comment]
Reset does the following as of now:

- Clear all memory locations < IO_AREA_START.
- Clear all registers.
- Clear the shadow registers.
- Reset all statistics counters.
- Disable interrupts and clear a possibly pending interrupt.
- Set the switch register to 3.

**Comment by sy2002** [comment]
OK, then I guess this is behaving as intended. Closing.
