### ISSUE TITLE
Emulator built-in disassembler should convert relative addresses 

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#167]
Hi Bernd,

in Version 1.6 you implemented issue #36 "Monitor built-in disassembler should convert relative addresses".

Yesterday, when debugging using the **emulator** I wondered: Woudn't be this exact feature also extremely useful for the emulator?

<img width="660" alt="grafik" src="https://user-images.githubusercontent.com/6825267/95990407-c2d42e00-0e2b-11eb-93b3-52f86e737d05.png">

**Comment by bernd-ulmann** [comment]
Done. :-)
