### ISSUE TITLE
Emulator does not correctly disassemble CMP 0, @R8

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#168]
Tested with the newest commit d6bf5cee7fc3d6545f6968c100c823b0cf0cc010

Here is a snippet from `monitor/monitor.lis`:

```
000930  0207  0FA0  FEEE  QMON$CHKORMNT               MOVE _SD$DEVICEHANDLE, R8
000931  0209  CFA1  0000                              CMP 0, @R8                       ; valid handle?
000932  020B  FFAB  0015                              RBRA QMON$CHKORMNT_E, !Z         ; yes: leave
000933  020D  0FA4  0001                              MOVE 1, R9                       ; partition #1
```

Here is, how the **Monitor** disassembles this part correctly:

```
0207 0FA0 MOVE    FEEE R8  
0209 CFA1 CMP     0000 @R8  
020B FFAB RBRA    0015 !Z		(-> 0222)
020D 0FA4 MOVE    0001 R9  
```

And here you can see, that the **Emulator** is not correctly disassembling `CMP 0, @R8` (but here is also an important disclaimer: I do suspect, that not only this instruction is disassembled wrongly, but also more/others, but I did not have the time in my today's lunch-break to test ;-) )

```
[0F60] Q> dis $0207, $0222
Disassembled contents of memory locations 0207 - 0222:
0207: 0FA0 MOVE  	0xFEEE, R08
0208: FEEE
0209: CFA1 CMP   	0x0000
020A: 0000
020B: FFAB RBRA  	0x0015, !Z	(-> 0222)
020C: 0015
```

**Comment by bernd-ulmann** [comment]
...it does now. :-)
