### ISSUE TITLE
Compiler interrupt bug

### ISSUE THREAD

**Issue by MJoergen** [sy2002/QNICE-FPGA#177]
The following piece of code:

```
long a = 0;
long b = 0;

static __interrupt void isr(void)
{
   if (!a)
      return;
   b += 1;
}
```

generates the following incorrect code (when compiled without optimization):

```
l1:
   move  #_a,R11
   cmp   @R11++,0
   rbra  l5,!z
   cmp   @R11++,0
   rbra  l5,!z
l4:
   move  @R13++,R15
l5:
   move  #_b,R12
   add   1,@R12++
   addc  0,@R12++
l2:
   rti
```

The instruction `move  @R13++,R15` should be replaced with a `rti`.

**Comment by sy2002** [comment]
Aha! The "return" leads to the `move @R13++,R15` and the "normal end of the function" leads to the `rti`. Good job! Interessting!

**Comment by MJoergen** [comment]
Fixed and verified.
