### ISSUE TITLE
Incorrect branch argument in intro document

### ISSUE THREAD

**Issue by MJoergen** [sy2002/QNICE-FPGA#185]
The pdf-document `qnice_intro.pdf` states on page 11 that the target of the four branch instructions (`ABRA`, `ASUB`, `RBRA`, `RSUB`) is the `dst` operand. This is incorrect, and should be `src` operand instead. The instruction decoding on page 9 is correct.

**Comment by bernd-ulmann** [comment]
Has been corrected in the intro slides as well as the programming card. :-)
