### ISSUE TITLE
Sift through TODO.txt and check for interessting stuff

### ISSUE THREAD

**Issue by sy2002** [sy2002/QNICE-FPGA#33]
@MJoergen I personally would be excited a lot about the VGA topic. But just in case: Here in [TODO.txt](https://github.com/sy2002/QNICE-FPGA/blob/develop/TODO.txt) are some more topics that you might want to have a look at for V1.7. In case you find something that you want to do: Just make an issue and assign it to yourself. In that case, please delete the item from `TODO.txt` as we try not to have redundancy between the issues list in GitHub and the `TODO.txt`. The latter one is more like a longterm "backlog"...

Please close this issue when you're done (independent from if you found anything in `TODO.txt` or not)

P.S. Of course feel free to add your own ideas to `TODO.txt` (longterm backlog) as well as to the GitHub issues.

**Comment by MJoergen** [comment]
Done. I added a wish for Ethernet support, and I created a new Issue #35 for the VGA module.
