### ISSUE TITLE
Bug in emulator: SHL/SHR does not correctly set N/Z, when src = 0

### ISSUE THREAD

**Issue by MJoergen** [sy2002/QNICE-FPGA#73]
The sequence:

```
MOVE    0x0000, R0
MOVE    0x0000, R1
MOVE    0x1234, R2
SHL     R0, R1
HALT
```

leaves the flags with N=1 and Z=0. I would expect N=0 and Z=1.

**Comment by sy2002** [comment]
This issue is related to issue #68 , so when fixing/closing it, then please also close #68

**Comment by bernd-ulmann** [comment]
Done - the emulator now passes the CPU test suite with a reassuring "OK" at the end. :-)
